name: escribo_estante_livros
description: "A new Flutter project to people read and download books."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.6

  #dependecias de downlaod
  dio: ^5.3.3
  vocsy_epub_viewer: ^2.0.0
  permission_handler: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
